# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

# Web Development Tools
gem 'haml'
gem 'coffee-script'
gem 'sass'

# API Support
gem 'sinatra'
gem 'activesupport'
